name: build and release version

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: release-x
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (static)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: huatuo/huatuo-bamai-static:${{ github.ref_name }}
      - name: Build and push (nostatic)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_MODE=nostatic
          tags: huatuo/huatuo-bamai:${{ github.ref_name }}

      - name: Extract files (static)
        run: |
          # same as docker build platforms
          set -euo pipefail
          platforms="amd64 arm64"
          for arch in $platforms; do
            tag=${{ github.ref_name }}
            tmpdir="huatuo-bamai-${tag}-static-linux-${arch}"
            tmp_container="tmp_${tag}_static_${arch}"
            docker create \
              --platform "linux/${arch}" \
              --name "${tmp_container}" \
              huatuo/huatuo-bamai-static:${tag}
            
            docker cp "${tmp_container}:/home/huatuo-bamai" .
            docker rm "${tmp_container}"
            mv huatuo-bamai $tmpdir
            cp LICENSE $tmpdir
            file $tmpdir/bin/huatuo-bamai
            tree $tmpdir
            tar zcf ${tmpdir}.tar.gz ${tmpdir}
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          token: ${{ secrets.HUATUO_RELEASE_TOKEN }}
          body_path: docs/CHANGELOG/CHANGELOG-${{ github.ref_name }}.md
          files: |
            huatuo-bamai-static-${{ github.ref_name }}-linux-*.tar.gz
