name: build and release project
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release-x:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: release-x
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: huatuo/huatuo-bamai:${{ github.ref_name }}
      - name: Extract files
        run: |
          # same as docker build platforms
          platforms="amd64 arm64"
          for arch in $platforms; do
            tag=${{ github.ref_name }}
            tmpdir="huatuo-${tag}-linux-${arch}"

            docker create --platform linux/${arch} --name tmp-container huatuo/huatuo-bamai:${tag}
            docker cp tmp-container:/home/huatuo-bamai .
            docker rm tmp-container

            mv huatuo-bamai $tmpdir

            cp LICENSE $tmpdir

            file $tmpdir/bin/huatuo-bamai

            tree $tmpdir
            tar zcf ${tmpdir}.tar.gz ${tmpdir}
          done

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          token: ${{ secrets.HUATUO_RELEASE_TOKEN }}
          fail_on_unmatched_files: true
          body_path: docs/CHANGELOG/CHANGELOG-${{ github.ref_name }}.md
          files: |
            huatuo-${{ github.ref_name }}-linux-*.tar.gz
